### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by rm20killer** [rm20killer/react-bot#6]
- [x]  work on upgrading to discord.js v13 

- [x]  fix issue with threads

- [x] fix ticket issues

- [x]  add "i am" response

- [ ]  add commands to give/remove people streamer/ticket ban
- [x] #33
